[package]
name = "bitvec"
version = "0.1.0"
authors = [
	"myrrlyn <myrrlyn@outlook.com>",
]
description = "A crate for manipulating memory one bit at a time"
documentation = "https://docs.rs/bitvec"
homepage = "https://myrrlyn.net/bitvec"
license = "MIT"
license-file = "LICENSE.txt"
repository = "https://github.com/myrrlyn/bitvec"

[dependencies]
